    export interface MenuItem {
    id: number;
    name: string;
    price: number;
    description: string;
    rating: number;
    imageUrl: string;
  }
  export const menuItems: MenuItem[] = [
    {
      id: 1,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_2.png',
    },
    {
      id: 2,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 3,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_3.png',
    },
    {
      id: 4,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 5,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 6,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 7,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 8,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 9,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 10,
      name: 'test',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {id: 1,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_2.png',
    },
    {
      id: 2,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 3,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_3.png',
    },
    {
      id: 4,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 5,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 6,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 7,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 8,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 9,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 10,
      name: 'test',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
      {id: 1,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_2.png',
    },
    {
      id: 2,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 3,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_3.png',
    },
    {
      id: 4,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 5,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 6,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 7,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 8,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 9,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {id: 1,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_2.png',
    },
    {
      id: 2,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 3,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_3.png',
    },
    {
      id: 4,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 5,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 6,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 7,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 8,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 9,
      name: 'Burger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {id: 1,
      name: 'Bánh mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_2.png',
    },
    {
      id: 2,
      name: 'Gà rán Popeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 3,
      name: 'Bur Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_3.png',
    },
    {
      id: 4,
      name: 'h mì nướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 5,
      name: 'Gà rán Popes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 6,
      name: 'Burison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 7,
      name: 'Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 8,
      name: 'Burg Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 9,
      name: 'Bur Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {id: 1,
      name: 'Bánh ớng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_2.png',
    },
    {
      id: 2,
      name: 'Gà rán Peyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 3,
      name: 'Burgerson',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_3.png',
    },
    {
      id: 4,
      name: 'Bánướng',
      price: 30.0,
      description: 'Củ dền, Khoai tây, Ớt chuông, Gia vị bánh mì',
      rating: 5.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 5,
      name: 'Gà rápeyes',
      price: 20.0,
      description: 'Gà rán giòn với gia vị đặc biệt, ăn kèm khoai tây chiên',
      rating: 4.0,
      imageUrl: '/images/images_foot/foot_1.png',
    },
    {
      id: 6,
      name: 'Bger Bison',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 7,
      name: 'Burger Bn',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 8,
      name: 'Burson',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 9,
      name: 'Burr Bon',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
    {
      id: 20,
      name: 'test',
      price: 50.0,
      description: 'Thịt bò Bison, phô mai, rau củ tươi, sốt đặc biệt',
      rating: 2.0,
      imageUrl: '/images/images_foot/foot_4.png',
    },
  ];